name: Run Tests

on:
  push:
    branches: [ "main" ] # Runs only when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
        continue-on-error: true

      - name: Run Flutter tests
        run: flutter test
